### ISSUE TITLE
better explain secrets folder

### ISSUE THREAD

**Issue by tommybananas** [simon-weber/gchatautorespond#5]
Do you know that all your private keys are public?

**Comment by simon-weber** [comment]
Only the ciphertext from https://github.com/elasticdog/transcrypt should be checked in. I double checked now and everything looks ok to me; did you find some plaintext?

**Comment by tommybananas** [comment]
Just wanted to double check that everything in the /secrets directory was in fact, not a secret.

**Comment by simon-weber** [comment]
Sounds good. I'll add a readme to that folder so it doesn't look so alarming 👍
